#!/bin/bash
cat >> logbook.html << EOF
<style>
    * {
        font-family: sans-serif;
    }
    .important {
        color: red;
        font-weight: bold;
    }
    .file {
        text-decoration: none;
        border: solid 1px;
        padding: 0.25em 0.5em 0.25em 0.5em;
        font-family: monospace;
    }
    .url {
        font-family: monospace;
    }
</style>

EOF
